eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.7/host:8761/eureka/
server:
  port: 8762


spring:
  application:
    name: eshop-product-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://172.17.0.5:3306/eshop
    username: eshop
    password: eshop

  rabbitmq:
    host: 172.17.0.2
    port: 5672
    username: rabbitadmin
    password: 123456